### ISSUE TITLE
【不兼容报告】本插件与 Geyser 不能同时加载

### ISSUE THREAD

**Issue by KaRuichin** [Flandre923/kook-chat-fabric-dev#5]
- 当Geyser与本插件同时加载时会出现以下报错并且服务端无法启动

我的fabric版本为当前最新版，尝试删除Geyser之后服务端可以正常启动

```
[15:01:29] [main/ERROR]: Mixin apply for mod fabrickookchat failed fabrickookchat.mixins.json:MixinServerPlayNetworkHandler from mod fabrickookchat -> net.minecraft.class
_3244: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_44337 in fabrickookchat.mixins.json:MixinServerPlayNetworkHandler fr
om mod fabrickookchat was not located in the target class net.minecraft.class_3244. Using refmap fabrickookchat-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_44337 in fabrickookchat.mixins.json:MixinServerPlayNetworkHandler from mod
 fabrickookchat was not located in the target class net.minecraft.class_3244. Using refmap fabrickookchat-refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar
:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:
0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.
5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin
.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.
12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
[15:01:29] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geyser-fabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabrickookchat.mixins.json:MixinServerPlayNetworkHandler from mod fabrickookchat] from phase [DE
FAULT] in config [fabrickookchat.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]

        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_44337 in fabrickookchat.mixins.json:MixinServerPlayNetworkHandl
er from mod fabrickookchat was not located in the target class net.minecraft.class_3244. Using refmap fabrickookchat-refmap.json
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar
:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:
0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.
5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin
.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.
12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.
5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$1(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4
f-bf4914a12a64cfcc.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.35+78d798af4f-b7e1d1d2d0d56cea.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.<clinit>(ServerPlayConnectionEvents.java:35) ~[fabric-networking-api-v1-3.1.2+78d798af4f-bf491
4a12a64cfcc.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onEnable(GeyserFabricMod.java:128) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onInitialize(GeyserFabricMod.java:89) ~[Geyser-Fabric.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more
```

**Comment by KaRuichin** [comment]
![image](https://github.com/Flandre923/kook-chat-fabric-dev/assets/69111766/7fb624ef-4abd-414c-8558-f0f5fa1dcec5)

加载了本插件之后似乎还会导致玩家无法加入服务器(验证用户名失败！)，如图所示
卸载后正常

**Comment by Flandre923** [comment]
无法登录是指正版或者使用了其他的登录信息后无法正常登录吗。

**Comment by Flandre923** [comment]
还有就是这个是fabric的服务器模组，不是插件。

**Comment by KaRuichin** [comment]
> 无法登录是指正版或者使用了其他的登录信息后无法正常登录吗。

我使用的是微软账号正版登陆

一开始我以为是我的账号信息过期了于是重新添加了一次账号，结果还是不行。
最后卸载了本模组后再尝试进入服务器就没有出现问题。

**Comment by Flandre923** [comment]
> > 无法登录是指正版或者使用了其他的登录信息后无法正常登录吗。
> 
> 我使用的是微软账号正版登陆
> 
> 一开始我以为是我的账号信息过期了于是重新添加了一次账号，结果还是不行。 最后卸载了本模组后再尝试进入服务器就没有出现问题。

 好的，等我这几天忙完了我看看。我确实直接干掉了一部分代码

**Comment by Flandre923** [comment]
请你告诉我的使用的模组的版本，以及游戏的版本

**Comment by Flandre923** [comment]
等我研究下Geyser ，正常的fabric服务器加这个mod是没有这个问题的。日志报错是找不到一个mixin使用的shadow的方法。

**Comment by Flandre923** [comment]
麻烦你提供下服务端吗，或者安装方法。我直接装Geyser mod是可以正常运行的。

**Comment by KaRuichin** [comment]
Java：21.0.1 64-bit
系统：Win11 23H2
服务端和游戏：1.20.4
Fabric：0.15.6


> 请你告诉我的使用的模组的版本，以及游戏的版本

**Comment by Flandre923** [comment]
好吧，目前模组还不支持1.20.4，支持1.20.2和1.20.1分别对于了1.0.1和1.0.0版本。我测试的1.20.2可以正常和geyser。目前我已经在尝试升级支持1.20.3和1.20.4了

**Comment by KaRuichin** [comment]
> 好吧，目前模组还不支持1.20.4，支持1.20.2和1.20.1分别对于了1.0.1和1.0.0版本。我测试的1.20.2可以正常和geyser。目前我已经在尝试升级支持1.20.3和1.20.4了

原来是这样，我以为它会向下兼容旧版本的模组
麻烦大佬了 >_<

**Comment by Flandre923** [comment]
支持1.20.4版本了。你试试吧

**Comment by KaRuichin** [comment]
> 支持1.20.4版本了。你试试吧

运行正常，感谢大佬 🥰
